# Uncomment the next line to define a global platform for your project
# platform :ios, '11.0'

target 'MiniChallenge' do

  use_frameworks!


  pod 'Firebase/Auth'
  pod 'Firebase/Core' 
  pod 'Firebase/Database'

  

end
